import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';

const PASSWORD_HASH_ALGORITHM = 'scrypt';
const SCRYPT_N = 16_384;
const SCRYPT_R = 8;
const SCRYPT_P = 1;
const KEY_LENGTH = 64;
const MAX_MEMORY = 64 * 1024 * 1024;

function decodeBase64Url(value) {
  return Buffer.from(value, 'base64url');
}

function safeEqual(left, right) {
  if (left.byteLength !== right.byteLength) {
    return false;
  }

  return timingSafeEqual(left, right);
}

export function createPasswordHash(password) {
  const salt = randomBytes(16).toString('base64url');
  const derived = scryptSync(password, salt, KEY_LENGTH, {
    N: SCRYPT_N,
    r: SCRYPT_R,
    p: SCRYPT_P,
    maxmem: MAX_MEMORY,
  });

  return [PASSWORD_HASH_ALGORITHM, SCRYPT_N, SCRYPT_R, SCRYPT_P, salt, derived.toString('base64url')].join('$');
}

export function parsePasswordHash(encodedHash) {
  const [algorithm, rawN, rawR, rawP, salt, hash] = encodedHash.split('$');
  const cost = Number(rawN);
  const blockSize = Number(rawR);
  const parallelization = Number(rawP);

  if (
    algorithm !== PASSWORD_HASH_ALGORITHM ||
    !Number.isInteger(cost) ||
    !Number.isInteger(blockSize) ||
    !Number.isInteger(parallelization) ||
    !salt ||
    !hash
  ) {
    throw new Error('AUTH_PASSWORD_HASH must use the scrypt hash format generated by npm run auth:hash.');
  }

  return {
    cost,
    blockSize,
    parallelization,
    salt,
    hash: decodeBase64Url(hash),
  };
}

export function verifyPassword(password, encodedHash) {
  const parsed = parsePasswordHash(encodedHash);
  const derived = scryptSync(password, parsed.salt, parsed.hash.byteLength, {
    N: parsed.cost,
    r: parsed.blockSize,
    p: parsed.parallelization,
    maxmem: MAX_MEMORY,
  });

  return safeEqual(derived, parsed.hash);
}
